---

- name: Install mailutils
  ansible.builtin.package:
    name: mailutils
    state: present
  become: true

- name: Move failmail service and validate
  notify: "reload systemd"
  block:
    - name: Move failmail service to host
      ansible.builtin.template:
        src: failmail.service
        dest: /etc/systemd/system/failmail@.service
        # does not work using Ansible
        # validate: "systemd-analyze verify %s"
        owner: root
        group: root
        mode: u=rw,g=r,o=r
      become: true
      register: fail_mail_template

    - name: Validate failmail service
      # validation as separate task
      ansible.builtin.command: systemd-analyze verify failmail@.service
      args:
        chdir: "/etc/systemd/system"
      changed_when: false
      become: true

# Taken from: https://www.freedesktop.org/software/systemd/man/systemd.unit.html
- name: Add failmail as a global OnFailure dependency
  block:
    - name: Add service.d for global config directory
      ansible.builtin.file:
        path: "{{ item }}"
        owner: root
        group: root
        state: directory
        mode: u=rwx,g=rx,o=rx
      become: true
      loop:
        - /etc/systemd/system/service.d/
        - /etc/systemd/system/failmail@.service.d/

    - name: Template global failure dependancy Unit file
      ansible.builtin.template:
        src: 10-all.conf.j2
        dest: /etc/systemd/system/service.d/10-all.conf
        owner: root
        group: root
        mode: u=rw,g=r,o=r
      become: true
      notify: "reload systemd"

    - name: Prevent infinite loops for failmail service itself (symlink)
      ansible.builtin.file:
        src: /dev/null
        dest: /etc/systemd/system/failmail@.service.d/10-all.conf
        owner: root
        group: root
        state: link
      become: true
